export const FETCH_RESTAURANTS_START = "FETCH_RESTAURANTS_START";
export const FETCH_RESTAURANTS_SUCCESS = "FETCH_RESTAURANTS_SUCCESS";
export const FETCH_RESTAURANTS_FAIL = "FETCH_RESTAURANTS_FAIL";

export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

export const FETCH_RESTAURANT_START = "FETCH_RESTAURANT_START";
export const FETCH_RESTAURANT_SUCCESS = "FETCH_RESTAURANT_SUCCESS";
export const FETCH_RESTAURANT_FAIL = "FETCH_RESTAURANT_FAIL";

export const FETCH_RESTAURANT_MENU_ITEMS_START =
  "FETCH_RESTAURANT_MENU_ITEMS_START";
export const FETCH_RESTAURANT_MENU_ITEMS_SUCCESS =
  "FETCH_RESTAURANT_MENU_ITEMS_SUCCESS";

export const AUTH_CODE_START = "AUTH_CODE_START";
export const AUTH_CODE_SUCCESS = "AUTH_CODE_SUCCESS";
export const AUTH_CODE_FAIL = "AUTH_CODE_FAIL";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const FETCH_RESTAURANT_COMMENTS_START =
  "FETCH_RESTAURANT_COMMENTS_START";
export const FETCH_RESTAURANT_COMMENTS_SUCCESS =
  "FETCH_RESTAURANT_COMMENTS_SUCCESS";
export const FETCH_RESTAURANT_COMMENTS_FAIL = "FETCH_RESTAURANT_COMMENTS_FAIL";

export const ADD_COMMENT_START = "ADD_COMMENT_START";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";


export const CAN_ADD_COMMENT_START = "CAN_ADD_COMMENT_START";
export const CAN_ADD_COMMENT_SUCCESS = "CAN_ADD_COMMENT_SUCCESS";
export const CAN_ADD_COMMENT_FAIL = "CAN_ADD_COMMENT_FAIL";

export const LAST_ORDER_COMMENT_START = "LAST_ORDER_COMMENT_START";
export const LAST_ORDER_COMMENT_SUCCESS = "LAST_ORDER_COMMENT_SUCCESS";
export const LAST_ORDER_COMMENT_FAIL = "LAST_ORDER_COMMENT_FAIL";


export const ADDRESS_START = "ADDRESS_START";
export const FETCH_ADDRESSES_SUCCESS = "FETCH_ADDRESSES_SUCCESS";
export const ADDRESS_FAIL = "ADDRESS_FAIL";

export const FETCH_BANNER_START = "FETCH_BANNER_START";
export const FETCH_BANNER_SUCCESS = "FETCH_BANNER_SUCCESS";

export const FETCH_MARKET_CATEGORIES_START = "FETCH_MARKET_CATEGORIES_START";
export const FETCH_MARKET_CATEGORIES_SUCCESS =
  "FETCH_MARKET_CATEGORIES_SUCCESS";

export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";

export const FETCH_WALLET_START = "FETCH_WALLET_START";
export const FETCH_WALLET_SUCCESS = "FETCH_WALLET_SUCCESS";

export const CHANGE_WALLET_START = "CHANGE_WALLET_START";
export const CHANGE_WALLET_SUCCESS = "CHANGE_WALLET_SUCCESS";


export const ADD_CART_START = "ADD_CART_START";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAIL = "ADD_CART_FAIL";

export const FETCH_CART_START = "FETCH_CART_START";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_FAIL = "FETCH_CART_FAIL";

export const REMOVE_CART_ITEM_START = "REMOVE_CART_ITEM_START";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const FETCH_CITIES_START = "FETCH_CITIES_START";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_FAIL = "FETCH_CITIES_FAIL";

export const FETCH_STREETS_START = "FETCH_STREETS_START";
export const FETCH_STREETS_SUCCESS = "FETCH_STREETS_SUCCESS";
export const FETCH_STREETS_FAIL = "FETCH_STREETS_FAIL";

export const FETCH_REGIONS_START = "FETCH_REGIONS_START";
export const FETCH_REGIONS_SUCCESS = "FETCH_REGIONS_SUCCESS";
export const FETCH_REGIONS_FAIL = "FETCH_REGIONS_FAIL";

export const ADD_ADDRESS_START = "ADD_ADDRESS_START";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL";

export const EDIT_ADDRESS_START = "EDIT_ADDRESS_START";
export const EDIT_ADDRESS_SUCCESS = "EDIT_ADDRESS_SUCCESS";
export const EDIT_ADDRESS_FAIL = "EDIT_ADDRESS_FAIL";

export const DELETE_ADDRESS_START = "DELETE_ADDRESS_START";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";

export const SET_SELECTED_ADDRESS = "SET_SELECTED_ADDRESS";


export const ADD_FAVORITE_ITEM_START = "ADD_FAVORITE_ITEM_START";
export const ADD_FAVORITE_ITEM_SUCCESS = "ADD_FAVORITE_ITEM_SUCCESS";
export const ADD_FAVORITE_ITEM_FAIL = "ADD_FAVORITE_ITEM_FAIL";

export const ADD_FAVORITE_RESTAURANT_START = "ADD_FAVORITE_RESTAURANT_START";
export const ADD_FAVORITE_RESTAURANT_SUCCESS = "ADD_FAVORITE_RESTAURANT_SUCCESS";
export const ADD_FAVORITE_RESTAURANT_FAIL = "ADD_FAVORITE_RESTAURANT_FAIL";



export const FETCH_FAVORITE_START = "FETCH_FAVORITE_START";
export const FETCH_FAVORITE_SUCCESS = "FETCH_FAVORITE_SUCCESS";
export const FETCH_FAVORITE_FAIL = "FETCH_FAVORITE_FAIL";

export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const REMOVE_NOTE_SUCCESS = "REMOVE_NOTE_SUCCESS";
export const FETCH_SUCCESS = "FETCH_SUCCESS";



export const FETCH_RECOMMENDED_ITEM_START = "FETCH_RECOMMENDED_ITEM_START";
export const FETCH_RECOMMENDED_ITEM_SUCCESS = "FETCH_RECOMMENDED_ITEM_SUCCESS";
export const FETCH_RECOMMENDED_ITEM_FAIL = "FETCH_RECOMMENDED_ITEM_FAIL";


export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const PAYMENT_START = "PAYMENT_START";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";


export const SAVE_ORDER_INFO_START = "SAVE_ORDER_INFO_START";
export const SAVE_ORDER_INFO_SUCCESS = "SAVE_ORDER_INFO_SUCCESS";
export const SAVE_ORDER_INFO_FAIL = "SAVE_ORDER_INFO_FAIL";


export const CANCEL_ORDER_START = "CANCEL_ORDER_START";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL";



export const FOLLOW_ORDER_START = "FOLLOW_ORDER_START";
export const FOLLOW_ORDER_SUCCESS = "FOLLOW_ORDER_SUCCESS";
export const FOLLOW_ORDER_FAIL = "FOLLOW_ORDER_FAIL";

export const UPDATE_FILTER_SUCCESS = "UPDATE_FILTER_SUCCESS";


export const SHOW_ERROR_SUCCESS = "SHOW_ERROR_SUCCESS";


export const FETCH_TOP_CATEGORIES_START = "FETCH_TOP_CATEGORIES_START";
export const FETCH_TOP_CATEGORIES_SUCCESS = "FETCH_TOP_CATEGORIES_SUCCESS";
export const FETCH_TOP_CATEGORIES_FAIL = "FETCH_TOP_CATEGORIES_FAIL";

export const FETCH_FILTERED_ITEMS_START = "FETCH_FILTERED_ITEMS_START";
export const FETCH_FILTERED_ITEMS_SUCCESS = "FETCH_FILTERED_ITEMS_SUCCESS";
export const FETCH_FILTERED_ITEMS_FAIL = "FETCH_FILTERED_ITEMS_FAIL";


export const UPDATE_RESTAURANT_FAVORITE_STATUS_SUCCESS = "UPDATE_RESTAURANT_FAVORITE_STATUS_SUCCESS";
export const UPDATE_ITEM_FAVORITE_STATUS_SUCCESS = "UPDATE_ITEM_FAVORITE_STATUS_SUCCESS";


export const SET_IS_MARKET_SUCCESS = "SET_IS_MARKET_SUCCESS";
